version: '3'

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  webapp:
    build:
      context: .
      dockerfile: Dockerfile.vulnerable
    ports:
      - '8080:8080'
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
