version: '3'

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  webapp:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8081:8080"  # Using a different port for the secure version
    depends_on:
      - mysql
    networks:
      - app-network
    environment:
      - SECURE_VERSION=true

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: 